 default: 
    target:dev
    dev:
       type: postgres
       threads: 4
       host: localhost
       port: 5432
       user: postgres
       pass: POS2021@sabi
       dbname: Automation_dbt
       schema: dbt_dev

    prod:
      target: prod
        prod:
          type: postgres
          threads: 1
          host: localhost
          port: 5432
          user: postgres
          pass: POS2021@sabi
          dbname: Automation_dbt
          schema: dbt_prod
 
 
